version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        build:
            context: .
        image: php:7-alpine
        container_name: server
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - app-network
    nuxt:
        build:
            context: ./frontend
        image: node:14-alpine
        container_name: client
        working_dir: /var/www
        command: npm run-script dev_docker
        environment:
            docker: "true"
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/var/www
        depends_on:
            - slim
        networks:
            - app-network
        stdin_open: true

networks:
    app-network:
        driver: bridge